name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "stedod21"
        git config --global user.email "stedod21@htl-kaindorf.at"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig README.md'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
